namespace HomeKit.Model
{
    public enum DeviceCategory
    {
        None = 0,
        Other = 1,
        Bridges = 2,
        Fans = 3,
        GarageDoorOpeners = 4,
        Lighting = 5,
        Locks = 6,
        Outlets = 7,
        Switches = 8,
        Thermostats = 9,
        Sensors = 10,
        SecuritySystems = 11,
        Doors = 12,
        Windows = 13,
        WindowCoverings = 14,
        ProgrammableSwitches = 15,
        Reserved = 16,
        IPCameras = 17,
        VideoDoorbells = 18,
        AirPurifiers = 19,
        Heaters = 20,
        AirConditioners = 21,
        Humidifiers = 22,
        Dehumidifiers = 23,
        Reserved24 = 24,
        Reserved25 = 25,
        Reserved26 = 26,
        Reserved27 = 27,
        Sprinklers = 28,
        Faucets = 29,
        ShowerSystems = 30,
        Reserved31 = 31,
        Remotes32 = 32,
    }
}